# srun - a minimal Wayland application launcher (xdg-shell + cairo + xkbcommon).
#
# The xdg-shell client protocol is generated by wayland-scanner from the
# system wayland-protocols XML, into the build directory (it is a build
# artifact, not kept in the source tree). Build layout mirrors swm:
# sources in src/, objects + binary + generated protocol in build/.

WAYLAND_PROTOCOLS = $(shell pkg-config --variable=pkgdatadir wayland-protocols)
XDG_XML = $(WAYLAND_PROTOCOLS)/stable/xdg-shell/xdg-shell.xml

CC        ?= gcc
CFLAGS    ?= -std=c11 -Wall -Wextra -O2 -g -D_GNU_SOURCE -MMD -MP
PKG_CONFIG ?= pkg-config

PKGS       = wayland-client xkbcommon cairo
CFLAGS    += $(shell $(PKG_CONFIG) --cflags $(PKGS))
CFLAGS    += -I$(BUILD_DIR)
LDLIBS    += $(shell $(PKG_CONFIG) --libs $(PKGS))

SRC_DIR    = src
BUILD_DIR  = build

# xdg-shell client protocol is generated into the build dir
GEN_H = $(BUILD_DIR)/xdg-shell-client-protocol.h
GEN_C = $(BUILD_DIR)/xdg-shell-protocol.c

SRCS = $(wildcard $(SRC_DIR)/*.c)
OBJS = $(SRCS:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o) $(BUILD_DIR)/xdg-shell-protocol.o
TARGET = $(BUILD_DIR)/srun

PREFIX    ?= $(HOME)/.local
DESTDIR   ?=
BINDIR     = $(DESTDIR)$(PREFIX)/bin

all: $(TARGET)

$(GEN_H) $(GEN_C): $(XDG_XML) | $(BUILD_DIR)
	wayland-scanner client-header $< $(GEN_H)
	wayland-scanner private-code  $< $(GEN_C)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/xdg-shell-protocol.o: $(GEN_C) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# the generated protocol header is included (via srun.h) by every source file
$(OBJS): $(GEN_H)

-include $(OBJS:.o=.d)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $@ $(LDLIBS)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

clean:
	rm -rf $(BUILD_DIR)

run: $(TARGET)
	$(TARGET)

install: $(TARGET)
	install -Dm755 $(TARGET) $(BINDIR)/$(notdir $(TARGET))

uninstall:
	rm -f $(BINDIR)/$(notdir $(TARGET))

.PHONY: all clean run install uninstall
